name: Pull Request
description: Submit a contribution to ElegantFin
title: "[PR] <Short title for your changes>"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please follow our [Contributor Guidelines](../CONTRIBUTING.md) and keep your PR focused on a single improvement or fix.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your changes and the reason behind them.
      placeholder: What did you change and why?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add before/after images of any visual changes.
      placeholder: Drag and drop or paste images here.
    validations:
      required: false
  - type: textarea
    id: testing
    attributes:
      label: Cross-platform Testing
      description: Describe how you verified this works across devices (e.g., desktop, mobile, TV).
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I followed the style conventions (`em` units, minimal media queries).
          required: true
        - label: I avoided unnecessary use of `!important`.
          required: true
        - label: I commented my code where applicable.
          required: true
        - label: I tested my changes across viewports.
          required: true